apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nginx_test.fullname" . }}
  labels:
    app: {{ template "nginx_test.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{.Values.service.type}}
  ports: 
    - port: {{.Values.service.externalPort}}
      targetPort: {{.Values.service.internalPort}}
      protocol: TCP
      name: {{.Values.service.name }}
  selector:
    app: {{ template "artifactory.name" . }}
    release: {{.Release.Name }}

#type: Opaque
#data:
#  {{ if .Values.nginx_testRootPassword }}
#  nginx_test-root-password:  {{ .Values.nginx_testRootPassword | b64enc | quote }}
##  {{ else }}
#  nginx_test-root-password: {{ randAlphaNum 10 | b64enc | quote }}
#  {{ end }}
#  {{ if .Values.nginx_testPassword }}
#  nginx_test-password:  {{ .Values.nginx_testPassword | b64enc | quote }}
#  {{ else }}
#  nginx_test-password: {{ randAlphaNum 10 | b64enc | quote }}
#  {{ end }}
