apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "nginx.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{.Values.service.type}}
  ports: 
    - port: {{.Values.service.externalPort}}
      targetPort: {{.Values.service.internalPort}}
      protocol: TCP
      name: {{.Values.service.name }}
  selector:
    app: {{ template "nginx.fullname" . }}
    release: {{.Release.Name }}

#type: Opaque
#data:
#  {{ if .Values.nginxRootPassword }}
#  nginx-root-password:  {{ .Values.nginxRootPassword | b64enc | quote }}
##  {{ else }}
#  nginx-root-password: {{ randAlphaNum 10 | b64enc | quote }}
#  {{ end }}
#  {{ if .Values.nginxPassword }}
#  nginx-password:  {{ .Values.nginxPassword | b64enc | quote }}
#  {{ else }}
#  nginx-password: {{ randAlphaNum 10 | b64enc | quote }}
#  {{ end }}
